Add clarifications to board and serial number descriptions
oneapi-src/level-zero-spec pull request #180
Opened 2023-07-19 21:46 UTC by aravindksg

Addresses #179

2023-07-19 21:46 UTC, aravindksg commented
@jandres742 @saik-intel  @vaidyan1-int @wdamon-intel for review

2023-07-19 22:01 UTC, jandres742 approved these changes

2023-07-20 14:36 UTC, wdamon-intel requested changes
There's an opportunity here to fix-up a couple of spelling errors.

2023-07-20 14:36 UTC, wdamon-intel commented on scripts/sysman/device.yml
> +      desc: "[out] Manufacturing serial number (NULL terminated string value). This value is intended to reflect the Part ID/SoC ID assigned by manufacturer that is unique for a SoC. Will be set to t
Might as well fixup the spelling for "unkown" -> "unknown", too.

2023-07-20 14:36 UTC, wdamon-intel commented on scripts/sysman/device.yml
> +      desc: "[out] Manufacturing board number (NULL terminated string value). Alternatively \"boardSerialNumber\", this value is intended to reflect the string printed on board label by manufacturer.
same

2023-07-20 16:31 UTC, aravindksg commented on scripts/sysman/device.yml
> +      desc: "[out] Manufacturing board number (NULL terminated string value). Alternatively \"boardSerialNumber\", this value is intended to reflect the string printed on board label by manufacturer.
done

2023-07-20 16:50 UTC, wdamon-intel approved these changes
LGTM

2023-07-20 16:51 UTC, merged