Extend the SYSMAN Frequency Domain list to include a MEDIA Domain
oneapi-src/level-zero-spec pull request #63
Opened 2023-01-17 16:11 UTC by pmmeyer

2023-01-17 16:16 UTC, jandres742 commented
@pmmeyer : thanks. This addresses https://github.com/oneapi-src/level-zero-spec/issues/60, correct?

@sanilkumar0 , @saik-intel: could you take a look?

2023-01-17 16:31 UTC, pmmeyer commented
> @pmmeyer : thanks. This addresses #60, correct?
> 
> @sanilkumar0 , @saik-intel: could you take a look?

Yes, that is correct.

2023-01-17 16:36 UTC, ezhilintc commented
> > @pmmeyer : thanks. This addresses #60, correct?
> > @sanilkumar0 , @saik-intel: could you take a look?
> 
> Yes, that is correct.

This addresses spec side of it. We still need some changes in sysman UMD, right?

2023-01-17 17:50 UTC, jandres742 commented
@ezhilintc : Correct. Once these changes are merged and released, we could start implementation in driver.

I think this could be added in next minor version, v1.6.

2023-01-17 22:12 UTC, ezhilintc approved these changes

2023-01-23 20:19 UTC, pmmeyer commented
@jandres742 - will someone be merging this PR? I don't seem to have permission.

2023-01-23 20:40 UTC, jandres742 commented
@pmmeyer thanks. We haven't merged this PR since we are targeting this for v1.6, since it is a change in enum. Before that, we are thinking on having another update, 1.5.X, so we will merge this afterwards. After merging, it will be released on 1.6 loader, and then absorbed by driver implementations.

Let me know if this helps.

2023-01-23 20:41 UTC, jandres742 requested changes
To be merged for v1.6.

2023-01-23 21:12 UTC, bmyates commented on scripts/sysman/frequency.yml
> +    - name: MEDIA
Add a `version: 1.6` guard to new addition

2023-01-23 21:12 UTC, bmyates commented
Code targeting 1.6 should be mergeable if it is properly guarded with version checks

2023-01-24 05:42 UTC, jandres742 commented
> Code targeting 1.6 should be mergeable if it is properly guarded with version checks

thanks @bmyates . You are correct. @pmmeyer : could you add the versioning?

2023-02-22 18:19 UTC, wdamon-intel commented
> could you add the versioning

@pmmeyer please follow up with the versioning tags.

2023-03-15 07:52 UTC, jandres742 approved these changes

2023-03-16 15:41 UTC, merged